# Generated by Django 4.1.4 on 2023-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluckingRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ha', models.FloatField()),
                ('total_days', models.FloatField()),
                ('ha_day_target', models.FloatField()),
                ('pluckers_req', models.FloatField()),
                ('daily_actual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PluckingRounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateTimeField()),
                ('plucking_date', models.IntegerField()),
                ('division', models.CharField(default=None, max_length=20)),
                ('zone', models.CharField(default=None, max_length=20)),
                ('field', models.IntegerField()),
                ('plucking_days', models.IntegerField()),
                ('plucking_rounds', models.IntegerField()),
            ],
        ),
    ]
