# Generated by Django 4.1.4 on 2023-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plucking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluckingPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_area', models.FloatField()),
                ('vp_division_area', models.FloatField()),
                ('seedling_division_area', models.FloatField()),
                ('vp_blocks_per_zone', models.FloatField()),
                ('seedling_blocks_per_zone', models.FloatField()),
                ('vp_zone_size', models.FloatField()),
                ('seedling_zone_size', models.FloatField()),
                ('vp_schemes_per_division', models.FloatField()),
                ('seedling_schemes_per_division', models.FloatField()),
                ('vp_rounds_per_zone', models.FloatField()),
                ('seedling_rounds_per_zone', models.FloatField()),
                ('total_working_days', models.FloatField()),
                ('total_pluckers_per_division', models.FloatField()),
                ('total_supervisors_per_division', models.FloatField()),
                ('total_schemes_per_division', models.FloatField()),
                ('public_holidays', models.FloatField()),
                ('paydays', models.FloatField()),
            ],
        ),
    ]
