# Generated by Django 4.1.4 on 2023-06-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plucking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisiondetails',
            old_name='sd_field_ha',
            new_name='field_ha',
        ),
        migrations.RemoveField(
            model_name='divisiondetails',
            name='sd_zone_field',
        ),
        migrations.RemoveField(
            model_name='divisiondetails',
            name='sd_zone_fields',
        ),
        migrations.RemoveField(
            model_name='divisiondetails',
            name='vp_field_ha',
        ),
        migrations.RemoveField(
            model_name='divisiondetails',
            name='vp_zone_field',
        ),
        migrations.RemoveField(
            model_name='divisiondetails',
            name='vp_zone_fields',
        ),
    ]
