# Generated by Django 4.1.4 on 2023-06-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plucking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autofields',
            old_name='Zone_F',
            new_name='Zone',
        ),
        migrations.RemoveField(
            model_name='autofields',
            name='Zone_E',
        ),
        migrations.RemoveField(
            model_name='autofields',
            name='Zone_G',
        ),
    ]
