# Generated by Django 4.1.4 on 2023-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plucking', '0002_pluckingplanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammedSchemePlucking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_quality', models.FloatField()),
                ('VP_percentage', models.FloatField()),
                ('SD_percentage', models.FloatField()),
                ('VP_division_area', models.FloatField()),
                ('SD_division_area', models.FloatField()),
                ('field_spacing', models.FloatField()),
                ('max_bag_kgs', models.IntegerField()),
                ('plucker_grade', models.CharField(default=None, max_length=20)),
                ('VP_lines', models.IntegerField()),
                ('SD_lines', models.IntegerField()),
                ('VP_line_bushes', models.IntegerField()),
                ('SD_line_bushes', models.IntegerField()),
                ('block_size', models.IntegerField()),
                ('VP_scheme', models.IntegerField()),
                ('SD_scheme', models.IntegerField()),
                ('VP_pluckers_ha', models.IntegerField()),
                ('SD_pluckers_ha', models.IntegerField()),
                ('VP_scheme_day', models.IntegerField()),
                ('SD_scheme_day', models.IntegerField()),
                ('VP_rounds', models.IntegerField()),
                ('SD_rounds', models.IntegerField()),
                ('pluckers', models.IntegerField()),
                ('zone_number', models.IntegerField()),
                ('zone_number_pluckers', models.IntegerField()),
                ('zone_number_supervisor', models.IntegerField()),
                ('zone_schemes_Max_day', models.IntegerField()),
                ('zone_scheme_moves_day', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='pluckingplanner',
            old_name='seedling_blocks_per_zone',
            new_name='sd_blocks_per_zone',
        ),
        migrations.RenameField(
            model_name='pluckingplanner',
            old_name='seedling_division_area',
            new_name='sd_division_area',
        ),
        migrations.RenameField(
            model_name='pluckingplanner',
            old_name='seedling_rounds_per_zone',
            new_name='sd_rounds_per_zone',
        ),
        migrations.RenameField(
            model_name='pluckingplanner',
            old_name='seedling_schemes_per_division',
            new_name='sd_schemes_per_division',
        ),
        migrations.RenameField(
            model_name='pluckingplanner',
            old_name='seedling_zone_size',
            new_name='sd_zone_size',
        ),
    ]
